export class Constants {
  public static readonly ROLE_STUDENT: string = 'STUDENT';
  public static readonly ROLE_TEACHER: string = 'TEACHER';
  public static readonly ROLE_ADMIN: string = 'ADMIN';

  public static readonly QUESTION_SINGLE: string = 'SINGLE';
  public static readonly QUESTION_MULTI: string = 'MULTI';
  public static readonly QUESTION_JUDGE: string = 'JUDGE';
  public static readonly QUESTION_BLANK: string = 'BLANK';
  public static readonly QUESTION_SHORT: string = 'SHORT';

  public static readonly EXAM_IN_PROGRESS: string = 'IN_PROGRESS';
  public static readonly EXAM_GRADING: string = 'GRADING';
  public static readonly EXAM_GRADED: string = 'GRADED';

  public static readonly MAX_SWITCH_COUNT: number = 3;
  public static readonly SYNC_INTERVAL_MS: number = 30000;
  public static readonly PROGRESS_INTERVAL_MS: number = 60000;

  public static readonly APP_NAME: string = '鸿蒙智学业';
  public static readonly APP_SLOGAN: string = '智启学业 · 航向未来';
  public static readonly PRIMARY_COLOR: string = '#304FFE';
}
